### ISSUE TITLE
spec_normalization_with_carbon.ipynb

### ISSUE THREAD

**Issue by cesar-nicolas-cuevas** [Beamlines-CanadianLightSource/SGMPy#40]
Hi!!!
When you run the code to check the bad spectra in the "C normalization with the blank" you get this error after In[20]
Hope you can solve it.
Best,
César

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-8889a9eef393> in <module>()
      1 bad_scan = inputText.value
----> 2 good_scan_index = generate_good_scan_index(index_of_scan_num, bad_scan)

C:\2016-CLS\24-7902\scripts\xas_binned.py in generate_good_scan_index(scan_num_index, bad_scan_index_str)
     10 
     11 def generate_good_scan_index(scan_num_index, bad_scan_index_str):
---> 12         length = len(scan_num_index)
     13         # if badScanStr is null, then return original arrays
     14         if bad_scan_index_str == '':

TypeError: object of type 'NoneType' has no len()

**Comment by Henry0422** [comment]
Hi Cesar,

I think the issue is because `scan_num_index `is None(null). 

Can you try this?
`good_scan_index = generate_good_scan_index(scan_num, bad_scan)`


scan_num is initialed and assigned at here:
`energy_array, mca_array, scaler_array, scan_num = open_all_sgm_xas(opened_file)`
