### ISSUE TITLE
EEM plots do not appear correctly

### ISSUE THREAD

**Issue by regiert** [Beamlines-CanadianLightSource/SGMPy#41]
When plotting a C K-edge data set using the following:
 
emission_energy_sdd1 = plot_excitation_emission_matrix(mean_energy_array, sdd_bin_data, "SDD4")

The resulting plot has an odd appearance that doesn't seem consistent with what is expected from the measurement.  When plotting the reduced XAS using ROIs, the spectra appear to have the expected shape.  It seems that there is a problem with the EEM plot that needs more investigation.

**Comment by regiert** [comment]
Problem appears to be related to the use of multiple individual calls to plt.scatter each using a normalized color scale in plot_excitation_emission_matrix.  Because the color scale is determined individually for each call to plt.scatter, the color bar used will be normalized to the maximum and minimum counts in each XRF spectrum.  Need to fix the range of the color scale to be the same for every call to plt.scatter in the for loop.

**Comment by regiert** [comment]
Adding appropriate 'vmax' and 'vmin' values to the plt.scatter call produces the correct image.

**Comment by Henry0422** [comment]
It looks better after add `vmax `and `vmin`. This issue may be reopen in the future, if we found something need to be improved again. For details about fixing this issue pleases check https://github.com/Beamlines-CanadianLightSource/SGMPy/commit/de8b3d65f8518e27094b9cfd43ef3424e66dc593
